### ISSUE TITLE
Day03 - your website

### ISSUE THREAD

**Issue by AdiBarelMeisel** [liroh99/Assignments#3]
Hey Liron! 
How do you feel during rotation period?
I really liked your website, you design it very nice and elegant!
What do you find interesting in cancer research?

Wish you good luck !
Adi!

@szabgab

**Comment by liroh99** [comment]
Hi Adi, thanks for the comment. 
I think understanding the heterogeneity of the disease and how to use that knowledge to develop specialized treatment is of interest to me, but of course, the field is huge.
